services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  producer:
    build:
      context: ./producer
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./fastf1_cache:/app/cache

  consumer:
    build:
      context: ./consumer
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - consumer