// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
// F1 Race Calendar 2020â€“2026
// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
const F1_CALENDAR = {
    2020: [
        { round: 1,  name: "Gran Premio de Austria",       country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 2,  name: "GP de Estiria",                country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 3,  name: "Gran Premio de HungrÃ­a",        country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 4,  name: "Gran Premio de Gran BretaÃ±a",   country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 5,  name: "GP 70 Aniversario",            country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 6,  name: "Gran Premio de EspaÃ±a",         country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 7,  name: "Gran Premio de BÃ©lgica",        country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 8,  name: "Gran Premio de Italia",         country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 9,  name: "GP de Toscana",                country: "ðŸ‡®ðŸ‡¹", circuit: "Mugello" },
        { round: 10, name: "Gran Premio de Rusia",          country: "ðŸ‡·ðŸ‡º", circuit: "Sochi Autodrom" },
        { round: 11, name: "Gran Premio de Eifel",          country: "ðŸ‡©ðŸ‡ª", circuit: "NÃ¼rburgring" },
        { round: 12, name: "Gran Premio de Portugal",       country: "ðŸ‡µðŸ‡¹", circuit: "Algarve International" },
        { round: 13, name: "Gran Premio de Emilia Romagna", country: "ðŸ‡®ðŸ‡¹", circuit: "Imola" },
        { round: 14, name: "Gran Premio de TurquÃ­a",        country: "ðŸ‡¹ðŸ‡·", circuit: "Istanbul Park" },
        { round: 15, name: "Gran Premio de BahrÃ©in",        country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 16, name: "GP de Sakhir",                 country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain Outer" },
        { round: 17, name: "Gran Premio de Abu Dhabi",      country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
    2021: [
        { round: 1,  name: "Gran Premio de BahrÃ©in",        country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 2,  name: "Gran Premio de Emilia Romagna", country: "ðŸ‡®ðŸ‡¹", circuit: "Imola" },
        { round: 3,  name: "Gran Premio de Portugal",       country: "ðŸ‡µðŸ‡¹", circuit: "Algarve International" },
        { round: 4,  name: "Gran Premio de EspaÃ±a",         country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 5,  name: "Gran Premio de MÃ³naco",         country: "ðŸ‡²ðŸ‡¨", circuit: "Circuit de Monaco" },
        { round: 6,  name: "Gran Premio de AzerbaiyÃ¡n",     country: "ðŸ‡¦ðŸ‡¿", circuit: "Baku City Circuit" },
        { round: 7,  name: "Gran Premio de Francia",        country: "ðŸ‡«ðŸ‡·", circuit: "Circuit Paul Ricard" },
        { round: 8,  name: "Gran Premio de Estiria",        country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 9,  name: "Gran Premio de Austria",        country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 10, name: "Gran Premio de Gran BretaÃ±a",   country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 11, name: "Gran Premio de HungrÃ­a",        country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 12, name: "Gran Premio de BÃ©lgica",        country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 13, name: "Gran Premio de PaÃ­ses Bajos",   country: "ðŸ‡³ðŸ‡±", circuit: "Circuit Zandvoort" },
        { round: 14, name: "Gran Premio de Italia",         country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 15, name: "Gran Premio de Rusia",          country: "ðŸ‡·ðŸ‡º", circuit: "Sochi Autodrom" },
        { round: 16, name: "Gran Premio de TurquÃ­a",        country: "ðŸ‡¹ðŸ‡·", circuit: "Istanbul Park" },
        { round: 17, name: "Gran Premio de Estados Unidos", country: "ðŸ‡ºðŸ‡¸", circuit: "Circuit of the Americas" },
        { round: 18, name: "Gran Premio de MÃ©xico",         country: "ðŸ‡²ðŸ‡½", circuit: "Autodromo Hermanos Rodriguez" },
        { round: 19, name: "Gran Premio de Brasil",         country: "ðŸ‡§ðŸ‡·", circuit: "Autodromo Jose Carlos Pace" },
        { round: 20, name: "Gran Premio de Arabia SaudÃ­",   country: "ðŸ‡¸ðŸ‡¦", circuit: "Jeddah Corniche Circuit" },
        { round: 21, name: "Gran Premio de Abu Dhabi",      country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
    2022: [
        { round: 1,  name: "Gran Premio de BahrÃ©in",        country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 2,  name: "Gran Premio de Arabia SaudÃ­",   country: "ðŸ‡¸ðŸ‡¦", circuit: "Jeddah Corniche Circuit" },
        { round: 3,  name: "Gran Premio de Australia",       country: "ðŸ‡¦ðŸ‡º", circuit: "Albert Park" },
        { round: 4,  name: "Gran Premio de Emilia Romagna",  country: "ðŸ‡®ðŸ‡¹", circuit: "Imola" },
        { round: 5,  name: "Gran Premio de Miami",           country: "ðŸ‡ºðŸ‡¸", circuit: "Miami International" },
        { round: 6,  name: "Gran Premio de EspaÃ±a",          country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 7,  name: "Gran Premio de MÃ³naco",          country: "ðŸ‡²ðŸ‡¨", circuit: "Circuit de Monaco" },
        { round: 8,  name: "Gran Premio de AzerbaiyÃ¡n",      country: "ðŸ‡¦ðŸ‡¿", circuit: "Baku City Circuit" },
        { round: 9,  name: "Gran Premio de CanadÃ¡",          country: "ðŸ‡¨ðŸ‡¦", circuit: "Circuit Gilles Villeneuve" },
        { round: 10, name: "Gran Premio de Gran BretaÃ±a",    country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 11, name: "Gran Premio de Austria",         country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 12, name: "Gran Premio de Francia",         country: "ðŸ‡«ðŸ‡·", circuit: "Circuit Paul Ricard" },
        { round: 13, name: "Gran Premio de HungrÃ­a",         country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 14, name: "Gran Premio de BÃ©lgica",         country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 15, name: "Gran Premio de PaÃ­ses Bajos",    country: "ðŸ‡³ðŸ‡±", circuit: "Circuit Zandvoort" },
        { round: 16, name: "Gran Premio de Italia",          country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 17, name: "Gran Premio de Singapur",        country: "ðŸ‡¸ðŸ‡¬", circuit: "Marina Bay Street Circuit" },
        { round: 18, name: "Gran Premio de JapÃ³n",           country: "ðŸ‡¯ðŸ‡µ", circuit: "Suzuka Circuit" },
        { round: 19, name: "Gran Premio de Estados Unidos",  country: "ðŸ‡ºðŸ‡¸", circuit: "Circuit of the Americas" },
        { round: 20, name: "Gran Premio de MÃ©xico",          country: "ðŸ‡²ðŸ‡½", circuit: "Autodromo Hermanos Rodriguez" },
        { round: 21, name: "Gran Premio de Brasil",          country: "ðŸ‡§ðŸ‡·", circuit: "Autodromo Jose Carlos Pace" },
        { round: 22, name: "Gran Premio de Abu Dhabi",       country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
    2023: [
        { round: 1,  name: "Gran Premio de BahrÃ©in",        country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 2,  name: "Gran Premio de Arabia SaudÃ­",   country: "ðŸ‡¸ðŸ‡¦", circuit: "Jeddah Corniche Circuit" },
        { round: 3,  name: "Gran Premio de Australia",       country: "ðŸ‡¦ðŸ‡º", circuit: "Albert Park" },
        { round: 4,  name: "Gran Premio de AzerbaiyÃ¡n",      country: "ðŸ‡¦ðŸ‡¿", circuit: "Baku City Circuit" },
        { round: 5,  name: "Gran Premio de Miami",           country: "ðŸ‡ºðŸ‡¸", circuit: "Miami International" },
        { round: 6,  name: "Gran Premio de MÃ³naco",          country: "ðŸ‡²ðŸ‡¨", circuit: "Circuit de Monaco" },
        { round: 7,  name: "Gran Premio de EspaÃ±a",          country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 8,  name: "Gran Premio de CanadÃ¡",          country: "ðŸ‡¨ðŸ‡¦", circuit: "Circuit Gilles Villeneuve" },
        { round: 9,  name: "Gran Premio de Austria",         country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 10, name: "Gran Premio de Gran BretaÃ±a",    country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 11, name: "Gran Premio de HungrÃ­a",         country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 12, name: "Gran Premio de BÃ©lgica",         country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 13, name: "Gran Premio de PaÃ­ses Bajos",    country: "ðŸ‡³ðŸ‡±", circuit: "Circuit Zandvoort" },
        { round: 14, name: "Gran Premio de Italia",          country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 15, name: "Gran Premio de Singapur",        country: "ðŸ‡¸ðŸ‡¬", circuit: "Marina Bay Street Circuit" },
        { round: 16, name: "Gran Premio de JapÃ³n",           country: "ðŸ‡¯ðŸ‡µ", circuit: "Suzuka Circuit" },
        { round: 17, name: "Gran Premio de Qatar",           country: "ðŸ‡¶ðŸ‡¦", circuit: "Losail International" },
        { round: 18, name: "Gran Premio de Estados Unidos",  country: "ðŸ‡ºðŸ‡¸", circuit: "Circuit of the Americas" },
        { round: 19, name: "Gran Premio de MÃ©xico",          country: "ðŸ‡²ðŸ‡½", circuit: "Autodromo Hermanos Rodriguez" },
        { round: 20, name: "Gran Premio de Brasil",          country: "ðŸ‡§ðŸ‡·", circuit: "Autodromo Jose Carlos Pace" },
        { round: 21, name: "Gran Premio de Las Vegas",       country: "ðŸ‡ºðŸ‡¸", circuit: "Las Vegas Street Circuit" },
        { round: 22, name: "Gran Premio de Abu Dhabi",       country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
    2024: [
        { round: 1,  name: "Gran Premio de BahrÃ©in",        country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 2,  name: "Gran Premio de Arabia SaudÃ­",   country: "ðŸ‡¸ðŸ‡¦", circuit: "Jeddah Corniche Circuit" },
        { round: 3,  name: "Gran Premio de Australia",       country: "ðŸ‡¦ðŸ‡º", circuit: "Albert Park" },
        { round: 4,  name: "Gran Premio de JapÃ³n",           country: "ðŸ‡¯ðŸ‡µ", circuit: "Suzuka Circuit" },
        { round: 5,  name: "Gran Premio de China",           country: "ðŸ‡¨ðŸ‡³", circuit: "Shanghai International" },
        { round: 6,  name: "Gran Premio de Miami",           country: "ðŸ‡ºðŸ‡¸", circuit: "Miami International" },
        { round: 7,  name: "Gran Premio de Emilia Romagna",  country: "ðŸ‡®ðŸ‡¹", circuit: "Imola" },
        { round: 8,  name: "Gran Premio de MÃ³naco",          country: "ðŸ‡²ðŸ‡¨", circuit: "Circuit de Monaco" },
        { round: 9,  name: "Gran Premio de CanadÃ¡",          country: "ðŸ‡¨ðŸ‡¦", circuit: "Circuit Gilles Villeneuve" },
        { round: 10, name: "Gran Premio de EspaÃ±a",          country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 11, name: "Gran Premio de Austria",         country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 12, name: "Gran Premio de Gran BretaÃ±a",    country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 13, name: "Gran Premio de HungrÃ­a",         country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 14, name: "Gran Premio de BÃ©lgica",         country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 15, name: "Gran Premio de PaÃ­ses Bajos",    country: "ðŸ‡³ðŸ‡±", circuit: "Circuit Zandvoort" },
        { round: 16, name: "Gran Premio de Italia",          country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 17, name: "Gran Premio de AzerbaiyÃ¡n",      country: "ðŸ‡¦ðŸ‡¿", circuit: "Baku City Circuit" },
        { round: 18, name: "Gran Premio de Singapur",        country: "ðŸ‡¸ðŸ‡¬", circuit: "Marina Bay Street Circuit" },
        { round: 19, name: "Gran Premio de Estados Unidos",  country: "ðŸ‡ºðŸ‡¸", circuit: "Circuit of the Americas" },
        { round: 20, name: "Gran Premio de MÃ©xico",          country: "ðŸ‡²ðŸ‡½", circuit: "Autodromo Hermanos Rodriguez" },
        { round: 21, name: "Gran Premio de Brasil",          country: "ðŸ‡§ðŸ‡·", circuit: "Autodromo Jose Carlos Pace" },
        { round: 22, name: "Gran Premio de Las Vegas",       country: "ðŸ‡ºðŸ‡¸", circuit: "Las Vegas Street Circuit" },
        { round: 23, name: "Gran Premio de Qatar",           country: "ðŸ‡¶ðŸ‡¦", circuit: "Losail International" },
        { round: 24, name: "Gran Premio de Abu Dhabi",       country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
    2025: [
        { round: 1,  name: "Gran Premio de Australia",       country: "ðŸ‡¦ðŸ‡º", circuit: "Albert Park" },
        { round: 2,  name: "Gran Premio de China",           country: "ðŸ‡¨ðŸ‡³", circuit: "Shanghai International" },
        { round: 3,  name: "Gran Premio de JapÃ³n",           country: "ðŸ‡¯ðŸ‡µ", circuit: "Suzuka Circuit" },
        { round: 4,  name: "Gran Premio de BahrÃ©in",         country: "ðŸ‡§ðŸ‡­", circuit: "Bahrain International" },
        { round: 5,  name: "Gran Premio de Arabia SaudÃ­",    country: "ðŸ‡¸ðŸ‡¦", circuit: "Jeddah Corniche Circuit" },
        { round: 6,  name: "Gran Premio de Miami",           country: "ðŸ‡ºðŸ‡¸", circuit: "Miami International" },
        { round: 7,  name: "Gran Premio de Emilia Romagna",  country: "ðŸ‡®ðŸ‡¹", circuit: "Imola" },
        { round: 8,  name: "Gran Premio de MÃ³naco",          country: "ðŸ‡²ðŸ‡¨", circuit: "Circuit de Monaco" },
        { round: 9,  name: "Gran Premio de EspaÃ±a",          country: "ðŸ‡ªðŸ‡¸", circuit: "Circuit de Barcelona" },
        { round: 10, name: "Gran Premio de CanadÃ¡",          country: "ðŸ‡¨ðŸ‡¦", circuit: "Circuit Gilles Villeneuve" },
        { round: 11, name: "Gran Premio de Austria",         country: "ðŸ‡¦ðŸ‡¹", circuit: "Red Bull Ring" },
        { round: 12, name: "Gran Premio de Gran BretaÃ±a",    country: "ðŸ‡¬ðŸ‡§", circuit: "Silverstone" },
        { round: 13, name: "Gran Premio de BÃ©lgica",         country: "ðŸ‡§ðŸ‡ª", circuit: "Spa-Francorchamps" },
        { round: 14, name: "Gran Premio de HungrÃ­a",         country: "ðŸ‡­ðŸ‡º", circuit: "Hungaroring" },
        { round: 15, name: "Gran Premio de PaÃ­ses Bajos",    country: "ðŸ‡³ðŸ‡±", circuit: "Circuit Zandvoort" },
        { round: 16, name: "Gran Premio de Italia",          country: "ðŸ‡®ðŸ‡¹", circuit: "Monza" },
        { round: 17, name: "Gran Premio de AzerbaiyÃ¡n",      country: "ðŸ‡¦ðŸ‡¿", circuit: "Baku City Circuit" },
        { round: 18, name: "Gran Premio de Singapur",        country: "ðŸ‡¸ðŸ‡¬", circuit: "Marina Bay Street Circuit" },
        { round: 19, name: "Gran Premio de Estados Unidos",  country: "ðŸ‡ºðŸ‡¸", circuit: "Circuit of the Americas" },
        { round: 20, name: "Gran Premio de MÃ©xico",          country: "ðŸ‡²ðŸ‡½", circuit: "Autodromo Hermanos Rodriguez" },
        { round: 21, name: "Gran Premio de Brasil",          country: "ðŸ‡§ðŸ‡·", circuit: "Autodromo Jose Carlos Pace" },
        { round: 22, name: "Gran Premio de Las Vegas",       country: "ðŸ‡ºðŸ‡¸", circuit: "Las Vegas Street Circuit" },
        { round: 23, name: "Gran Premio de Qatar",           country: "ðŸ‡¶ðŸ‡¦", circuit: "Losail International" },
        { round: 24, name: "Gran Premio de Abu Dhabi",       country: "ðŸ‡¦ðŸ‡ª", circuit: "Yas Marina Circuit" },
    ],
};

// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
// Driver rosters by season
// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
const SEASON_DRIVERS = {
    2020: {
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "mercedes" },
        "77": { abbr: "BOT", name: "Valtteri Bottas",    team: "mercedes" },
        "5":  { abbr: "VET", name: "Sebastian Vettel",   team: "ferrari" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "33": { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "23": { abbr: "ALB", name: "Alexander Albon",    team: "red_bull" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "mclaren" },
        "11": { abbr: "PER", name: "Sergio PÃ©rez",       team: "racing_point" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "racing_point" },
        "31": { abbr: "OCO", name: "Esteban Ocon",       team: "renault" },
        "3":  { abbr: "RIC", name: "Daniel Ricciardo",   team: "renault" },
        "8":  { abbr: "GRO", name: "Romain Grosjean",    team: "haas" },
        "20": { abbr: "MAG", name: "Kevin Magnussen",    team: "haas" },
        "7":  { abbr: "RAI", name: "Kimi RÃ¤ikkÃ¶nen",     team: "alfa_romeo" },
        "99": { abbr: "GIO", name: "Antonio Giovinazzi", team: "alfa_romeo" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alphatauri" },
        "26": { abbr: "KVY", name: "Daniil Kvyat",       team: "alphatauri" },
        "6":  { abbr: "LAT", name: "Nicholas Latifi",    team: "williams" },
        "63": { abbr: "RUS", name: "George Russell",     team: "williams" },
    },
    2021: {
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "mercedes" },
        "77": { abbr: "BOT", name: "Valtteri Bottas",    team: "mercedes" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "ferrari" },
        "33": { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "11": { abbr: "PER", name: "Sergio PÃ©rez",       team: "red_bull" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "3":  { abbr: "RIC", name: "Daniel Ricciardo",   team: "mclaren" },
        "14": { abbr: "ALO", name: "Fernando Alonso",    team: "alpine" },
        "31": { abbr: "OCO", name: "Esteban Ocon",       team: "alpine" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "aston_martin" },
        "5":  { abbr: "VET", name: "Sebastian Vettel",   team: "aston_martin" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alphatauri" },
        "22": { abbr: "TSU", name: "Yuki Tsunoda",       team: "alphatauri" },
        "7":  { abbr: "RAI", name: "Kimi RÃ¤ikkÃ¶nen",     team: "alfa_romeo" },
        "99": { abbr: "GIO", name: "Antonio Giovinazzi", team: "alfa_romeo" },
        "47": { abbr: "MSC", name: "Mick Schumacher",    team: "haas" },
        "9":  { abbr: "MAZ", name: "Nikita Mazepin",     team: "haas" },
        "6":  { abbr: "LAT", name: "Nicholas Latifi",    team: "williams" },
        "63": { abbr: "RUS", name: "George Russell",     team: "williams" },
    },
    2022: {
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "mercedes" },
        "63": { abbr: "RUS", name: "George Russell",     team: "mercedes" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "ferrari" },
        "1":  { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "11": { abbr: "PER", name: "Sergio PÃ©rez",       team: "red_bull" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "3":  { abbr: "RIC", name: "Daniel Ricciardo",   team: "mclaren" },
        "14": { abbr: "ALO", name: "Fernando Alonso",    team: "alpine" },
        "31": { abbr: "OCO", name: "Esteban Ocon",       team: "alpine" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "aston_martin" },
        "5":  { abbr: "VET", name: "Sebastian Vettel",   team: "aston_martin" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alphatauri" },
        "22": { abbr: "TSU", name: "Yuki Tsunoda",       team: "alphatauri" },
        "77": { abbr: "BOT", name: "Valtteri Bottas",    team: "alfa_romeo" },
        "24": { abbr: "ZHO", name: "Guanyu Zhou",        team: "alfa_romeo" },
        "47": { abbr: "MSC", name: "Mick Schumacher",    team: "haas" },
        "20": { abbr: "MAG", name: "Kevin Magnussen",    team: "haas" },
        "6":  { abbr: "LAT", name: "Nicholas Latifi",    team: "williams" },
        "23": { abbr: "ALB", name: "Alexander Albon",    team: "williams" },
    },
    2023: {
        "1":  { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "11": { abbr: "PER", name: "Sergio PÃ©rez",       team: "red_bull" },
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "mercedes" },
        "63": { abbr: "RUS", name: "George Russell",     team: "mercedes" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "ferrari" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "81": { abbr: "PIA", name: "Oscar Piastri",      team: "mclaren" },
        "14": { abbr: "ALO", name: "Fernando Alonso",    team: "aston_martin" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "aston_martin" },
        "31": { abbr: "OCO", name: "Esteban Ocon",       team: "alpine" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alpine" },
        "23": { abbr: "ALB", name: "Alexander Albon",    team: "williams" },
        "2":  { abbr: "SAR", name: "Logan Sargeant",     team: "williams" },
        "22": { abbr: "TSU", name: "Yuki Tsunoda",       team: "alphatauri" },
        "21": { abbr: "DEV", name: "Nyck De Vries",      team: "alphatauri" },
        "77": { abbr: "BOT", name: "Valtteri Bottas",    team: "alfa_romeo" },
        "24": { abbr: "ZHO", name: "Guanyu Zhou",        team: "alfa_romeo" },
        "20": { abbr: "MAG", name: "Kevin Magnussen",    team: "haas" },
        "27": { abbr: "HUL", name: "Nico HÃ¼lkenberg",    team: "haas" },
    },
    2024: {
        "1":  { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "11": { abbr: "PER", name: "Sergio PÃ©rez",       team: "red_bull" },
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "mercedes" },
        "63": { abbr: "RUS", name: "George Russell",     team: "mercedes" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "ferrari" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "81": { abbr: "PIA", name: "Oscar Piastri",      team: "mclaren" },
        "14": { abbr: "ALO", name: "Fernando Alonso",    team: "aston_martin" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "aston_martin" },
        "31": { abbr: "OCO", name: "Esteban Ocon",       team: "alpine" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alpine" },
        "23": { abbr: "ALB", name: "Alexander Albon",    team: "williams" },
        "2":  { abbr: "SAR", name: "Logan Sargeant",     team: "williams" },
        "22": { abbr: "TSU", name: "Yuki Tsunoda",       team: "rb" },
        "3":  { abbr: "RIC", name: "Daniel Ricciardo",   team: "rb" },
        "77": { abbr: "BOT", name: "Valtteri Bottas",    team: "sauber" },
        "24": { abbr: "ZHO", name: "Guanyu Zhou",        team: "sauber" },
        "20": { abbr: "MAG", name: "Kevin Magnussen",    team: "haas" },
        "27": { abbr: "HUL", name: "Nico HÃ¼lkenberg",    team: "haas" },
    },
    2025: {
        "1":  { abbr: "VER", name: "Max Verstappen",     team: "red_bull" },
        "4":  { abbr: "NOR", name: "Lando Norris",       team: "mclaren" },
        "81": { abbr: "PIA", name: "Oscar Piastri",      team: "mclaren" },
        "16": { abbr: "LEC", name: "Charles Leclerc",    team: "ferrari" },
        "44": { abbr: "HAM", name: "Lewis Hamilton",     team: "ferrari" },
        "63": { abbr: "RUS", name: "George Russell",     team: "mercedes" },
        "12": { abbr: "ANT", name: "Kimi Antonelli",     team: "mercedes" },
        "14": { abbr: "ALO", name: "Fernando Alonso",    team: "aston_martin" },
        "18": { abbr: "STR", name: "Lance Stroll",       team: "aston_martin" },
        "87": { abbr: "BEA", name: "Oliver Bearman",     team: "haas" },
        "50": { abbr: "MAL", name: "Esteban Ocon",       team: "haas" },
        "30": { abbr: "LAW", name: "Liam Lawson",        team: "red_bull" },
        "22": { abbr: "TSU", name: "Yuki Tsunoda",       team: "rb" },
        "6":  { abbr: "HAD", name: "Isack Hadjar",       team: "rb" },
        "43": { abbr: "COL", name: "Franco Colapinto",   team: "alpine" },
        "10": { abbr: "GAS", name: "Pierre Gasly",       team: "alpine" },
        "55": { abbr: "SAI", name: "Carlos Sainz",       team: "williams" },
        "23": { abbr: "ALB", name: "Alexander Albon",    team: "williams" },
        "38": { abbr: "BOR", name: "Gabriel Bortoleto",  team: "sauber" },
        "27": { abbr: "HUL", name: "Nico HÃ¼lkenberg",    team: "sauber" },
    },
};

const SEASON_TEAMS = {
    2020: {
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        red_bull:     { name: "Red Bull Racing",    color: "#1E3D76" },
        ferrari:      { name: "Ferrari",            color: "#DC0000" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        racing_point: { name: "Racing Point",       color: "#F596C8" },
        renault:      { name: "Renault",            color: "#FFF500" },
        alphatauri:   { name: "AlphaTauri",         color: "#2B4562" },
        alfa_romeo:   { name: "Alfa Romeo",         color: "#960000" },
        haas:         { name: "Haas F1 Team",       color: "#787878" },
        williams:     { name: "Williams",           color: "#005AFF" },
    },
    2021: {
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        red_bull:     { name: "Red Bull Racing",    color: "#1E3D76" },
        ferrari:      { name: "Ferrari",            color: "#DC0000" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        alpine:       { name: "Alpine",             color: "#0090FF" },
        aston_martin: { name: "Aston Martin",       color: "#006F62" },
        alphatauri:   { name: "AlphaTauri",         color: "#2B4562" },
        alfa_romeo:   { name: "Alfa Romeo",         color: "#960000" },
        haas:         { name: "Haas F1 Team",       color: "#787878" },
        williams:     { name: "Williams",           color: "#005AFF" },
    },
    2022: {
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        red_bull:     { name: "Red Bull Racing",    color: "#3671C6" },
        ferrari:      { name: "Ferrari",            color: "#E8002D" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        alpine:       { name: "Alpine",             color: "#0090FF" },
        aston_martin: { name: "Aston Martin",       color: "#358C75" },
        alphatauri:   { name: "AlphaTauri",         color: "#5E8FAA" },
        alfa_romeo:   { name: "Alfa Romeo",         color: "#C92D4B" },
        haas:         { name: "Haas F1 Team",       color: "#B6BABD" },
        williams:     { name: "Williams",           color: "#64C4FF" },
    },
    2023: {
        red_bull:     { name: "Red Bull Racing",    color: "#3671C6" },
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        ferrari:      { name: "Ferrari",            color: "#E8002D" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        aston_martin: { name: "Aston Martin",       color: "#358C75" },
        alpine:       { name: "Alpine",             color: "#FF87BC" },
        williams:     { name: "Williams",           color: "#64C4FF" },
        alphatauri:   { name: "AlphaTauri",         color: "#5E8FAA" },
        alfa_romeo:   { name: "Alfa Romeo",         color: "#C92D4B" },
        haas:         { name: "Haas F1 Team",       color: "#B6BABD" },
    },
    2024: {
        red_bull:     { name: "Red Bull Racing",    color: "#3671C6" },
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        ferrari:      { name: "Ferrari",            color: "#E8002D" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        aston_martin: { name: "Aston Martin",       color: "#358C75" },
        alpine:       { name: "Alpine",             color: "#FF87BC" },
        williams:     { name: "Williams",           color: "#64C4FF" },
        rb:           { name: "RB (AlphaTauri)",    color: "#6692FF" },
        sauber:       { name: "Kick Sauber",        color: "#52E252" },
        haas:         { name: "Haas F1 Team",       color: "#B6BABD" },
    },
    2025: {
        red_bull:     { name: "Red Bull Racing",    color: "#3671C6" },
        mclaren:      { name: "McLaren",            color: "#FF8000" },
        ferrari:      { name: "Ferrari",            color: "#E8002D" },
        mercedes:     { name: "Mercedes",           color: "#00D2BE" },
        aston_martin: { name: "Aston Martin",       color: "#358C75" },
        alpine:       { name: "Alpine",             color: "#FF87BC" },
        haas:         { name: "Haas F1 Team",       color: "#B6BABD" },
        rb:           { name: "Racing Bulls",       color: "#6692FF" },
        williams:     { name: "Williams",           color: "#64C4FF" },
        sauber:       { name: "Sauber / Audi",      color: "#52E252" },
    },
};

